import { PresaleType } from "@/types";

export const presales: PresaleType[] = [
    {
        id: 1,
        banner: "interworld/interworld-banner.webp",
        logo: "padb/blendPadIcon.jpg",
        networkLogo: "padb/bsc.webp",
        typeImage: "/interworld/2.svg",
        title: "BlendPad Public Sale",
        type: "Presale",
        maxBuy: 50000,
        status: "Active",
        progress: 100,
        tags: ["KYC+", "AUDIT"],
        target: 1000000,
        raised: 1000,
        softcap: 30000,
        currency: "USDT",
        hardcap: "1M",
        rate: "2ITW",
        lock: "Manual",
        address: "0xF3606E68C5A600dE7f15C2a143976B1D5394bca6",
        network: "bsc",
        tabs: [
            {
                id: 1,
                name: "About",
                content:
                    "BlendPad.com is revolutionizing the way projects launch and grow in the decentralized finance (DeFi) space. Our platform leverages innovative AI-based technology, transparent governance, and robust community engagement to provide a seamless and secure environment for new projects to thrive. All services are designed to be one-click, ensuring ease of use with comprehensive community support.",
                ytVideo: "https://youtu.be/ijg1s_bjf2Q",
            },
            {
                id: 2,
                name: "Sale",
                network: "bsc",
                presaleAddress: "0x4739Dabf137A7367Bd042aC3c2DF1c80228a1be3",
                tokenName: "BlendPad",
                tokenSymbol: "PADB",
                totalSupply: 3681541.1,
                tokensForPresale: 2000000,
                softcap: 300000,
                hardcap: 1000000,
                unusedTokens: "Refund",
                presaleStartTime: "2024-02-14 13:00",
                presaleEndTime: "2024-02-28 13:00",
                liquidityPercent: "Manual Listing",
                tokensReleasedOnLaunch: "8",
                vestingDelay: 30,
                VestingTimePeriod: 30,
                vestingReleasePerTimePeriod: "8",
            },
            {
                id: 3,
                name: "Tokenomics",
                presale: 54.3251,
                unlocked: 45.6749,
                initialMarketCap: 0,
                circulatingMarketCap: 0,
                fdvMarketCap: 0,
            },
            {
                id: 4,
                name: "Locks",
                tokenLocks: 0,
                liquidityLocks: 0,
                tokenSymbol: "ITW",
            },
            {
                id: 5,
                name: "Team",
                members: [
                    {
                        name: "Interworld",
                        title: "Owner",
                        twitter: "https://twitter.com/interworld_io",
                        avatar: "interworld/interworld-logo.webp"
                    },
                ],
            },
        ],
        stats: [
            {
                status: "finalized",
                minimumBuy: "50",
                maxiumumBuy: "50",
                presaleRate: "2ITW",
                listingRate: "2ITW",
                totalContributors: 1272,
                avgContribution: 78616352,
                myContribution: 0,
                myReservedTokens: 0,
                tokenAddress: "0x64F7e4B5B48654c45476ADbc7800a78D3f577C8d",
            },
        ],
        updates: [
            {
                id: 1,
                dateFrom: "3 months ago",
                content:
                    "If you need assets on Abey - 1. Bridge USDT on XPlus (https://x.plus) 2. Or purchase ABEY on LBank (https://lbank.com/trade/abey_usdt) then sell on XSwap (https://xswap.com)",
            },
        ],
    },
    {
        id: 2,
        banner: "interworld/interworld-banner.webp",
        logo: "interworld/interworld-logo.webp",
        networkLogo: "interworld/abey.webp",
        typeImage: "/interworld/2.svg",
        title: "InterWorld Metaverse Presale #1",
        type: "Presale",
        maxBuy: 50000,
        status: "finalized",
        progress: 100,
        tags: ["KYC+", "AUDIT"],
        target: 1000000,
        raised: 1000000,
        softcap: 300000,
        currency: "USDT",
        hardcap: "1M",
        rate: "2ITW",
        lock: "Manual",
        address: "0xD644BdAF8627118d723168e5083864c041CdC2d5",
        network: "abbey",
        tabs: [
            {
                id: 1,
                name: "About",
                content:
                    "InterWorld is an upcoming metaverse built on the Abey blockchain with UE5 graphics. The teaser concert features @whoisdvrko's performance in our alpha launch.",
                ytVideo: "https://youtu.be/ijg1s_bjf2Q",
            },
            {
                id: 2,
                name: "Sale",
                network: "abbey",
                presaleAddress: "0xD644BdAF8627118d723168e5083864c041CdC2d5",
                tokenName: "InterWorld Token",
                tokenSymbol: "ITW",
                totalSupply: 3681541.1,
                tokensForPresale: 2000000,
                softcap: 300000,
                hardcap: 1000000,
                unusedTokens: "Refund",
                presaleStartTime: "2024-02-14 13:00",
                presaleEndTime: "2024-02-28 13:00",
                liquidityPercent: "Manual Listing",
                tokensReleasedOnLaunch: "8",
                vestingDelay: 30,
                VestingTimePeriod: 30,
                vestingReleasePerTimePeriod: "8",
            },
            {
                id: 3,
                name: "Tokenomics",
                presale: 54.3251,
                unlocked: 45.6749,
                initialMarketCap: 0,
                circulatingMarketCap: 0,
                fdvMarketCap: 0,
            },
            {
                id: 4,
                name: "Locks",
                tokenLocks: 0,
                liquidityLocks: 0,
                tokenSymbol: "ITW",
            },
            {
                id: 5,
                name: "Team",
                members: [
                    {
                        name: "Interworld",
                        title: "Owner",
                        twitter: "https://twitter.com/interworld_io",
                        avatar: "interworld/interworld-logo.webp"
                    },
                ],
            },
        ],
        stats: [
            {
                status: "finalized",
                minimumBuy: "50",
                maxiumumBuy: "50",
                presaleRate: "2ITW",
                listingRate: "2ITW",
                totalContributors: 1272,
                avgContribution: 78616352,
                myContribution: 0,
                myReservedTokens: 0,
                tokenAddress: "0x64F7e4B5B48654c45476ADbc7800a78D3f577C8d",
            },
        ],
        updates: [
            {
                id: 1,
                dateFrom: "3 months ago",
                content:
                    "If you need assets on Abey - 1. Bridge USDT on XPlus (https://x.plus) 2. Or purchase ABEY on LBank (https://lbank.com/trade/abey_usdt) then sell on XSwap (https://xswap.com)",
            },
        ],
    },
    {
        id: 3,
        banner: "pyggetton/pyggetton-banner.webp",
        logo: "pyggetton/pyggetton-logo.webp",
        networkLogo: "pyggetton/QuickIntel.png",
        typeImage: "/pyggetton/2.svg",
        title: "PYGGETON",
        type: "Fair Launch",
        maxBuy: 1000,
        status: "Sale Live",
        progress: 8,
        tags: ["KYC+", "AUDIT"],
        target: 1000000,
        raised: 412757,
        currency: "USDT",
        softcap: 5000,
        hardcap: "0",
        rate: "TBD",
        lock: "Manual",
        address: "0xe8EE725937148B325Ad524F4316341Aa9D626187",
        network: "abbey",
        tabs: [
            {
                id: 1,
                name: "About",
                content:
                    "🐷 We believe in the power of a decentralized future and self-sovereignty at scale.",
                ytVideo: "https://youtu.be/WCnaQBdOnCs",
            },
            {
                id: 2,
                name: "Sale",
                network: "abbey",
                presaleAddress: "0x116D4b50705d3F8A70DA74628CF2074574ed098E",
                tokenName: "PYGGETON",
                tokenSymbol: "PYGG",
                totalSupply: 420000000,
                tokensForPresale: 220000000,
                softcap: 5000,
                hardcap: 0,
                presaleStartTime: "2024-05-16 18:00",
                presaleEndTime: "2024-05-22 19:00",
                liquidityPercent: "Manual Listing",
            },
            {
                id: 3,
                name: "Tokenomics",
                presale: 52.381,
                unlocked: 47.619,
                initialMarketCap: 9545,
                circulatingMarketCap: 9545,
                fdvMarketCap: 9545,
            },
            {
                id: 4,
                name: "Locks",
                tokenLocks: 0,
                liquidityLocks: 0,
                tokenSymbol: "PYGG",
            },
            {
                id: 5,
                name: "Team",
                members: [
                    {
                        name: "anonc7a8afd-2",
                        avatar: "images/presales/pyggeton/avatar.svg",
                        title: "Owner",

                    },
                ],
            },
        ],
        stats: [
            {
                status: "Fair Launch",
                minimumBuy: "0",
                maxiumumBuy: "1000",
                presaleRate: "533,000.837 PYGG",
                listingRate: "533,000.837 PYGG",
                totalContributors: 12,
                avgContribution: 34.39644,
                myContribution: 0,
                myReservedTokens: 0,
                tokenAddress: "0xe8EE725937148B325Ad524F4316341Aa9D626187",
            },
        ],
    },
    {
        id: 4,
        banner: "scottish-cat/scottish-cat-banner.mp4",
        logo: "scottish-cat/scottish-cat-logo.webp",
        networkLogo: "scottish-cat/sol.webp",
        typeImage: "/scottish-cat/5.svg",
        title: "Scottish Cat",
        type: "Presale",
        maxBuy: 50000,
        status: "Launched",
        progress: 36,
        tags: ["AUDIT"],
        target: 5000,
        raised: 412.757,
        softcap: 5000,
        hardcap: "0",
        currency: "SOL",
        liquidity: 60,
        lock: "365 Days",
        address: "0x64F7e4B5B48654c45476ADbc7800a78D3f577C8d",
        network: "solana",
        tabs: [
            {
                id: 1,
                name: "About",
                content:
                    "$SCOT is a Solana-based token,  We're not just another meme token — there's a twist in our plot 😜",
                ytVideo: "https://youtu.be/yZ8gtKAU2sg",
            },
            {
                id: 2,
                name: "Sale",
                network: "solana",
                presaleAddress: "4yMxNNFJL3ihhKM3YUPVRsCNjLhfmiEhubh4r181Qcsx",
                tokenName: "Scottish",
                tokenSymbol: "$SCOT",
                totalSupply: 10000000000,
                tokensForPresale: 3750000000,
                tokensForLiquidity: 2025000000,
                softcap: 750,
                hardcap: 1500,

                presaleStartTime: "2024-05-02 15:00",
                presaleEndTime: "2024-05-04 15:00",
                liquidityPercent: "60",
                liquidityUnlockTime: "2025-05-06 15:29",
            },
            {
                id: 3,
                name: "Tokenomics",
                presale: 24.2781,
                liquidity: 13.1102,
                unlocked: 62.6117,
                score: "37.39 - Medium",
                initialMarketCap: 143135,
                circulatingMarketCap: 763390,
                fdvMarketCap: 763390,
            },
            {
                id: 4,
                name: "Locks",
                tokenLocks: 0,
                liquidityLocks: 0,
                tokenSymbol: "$SCOT",
            },
        ],
        stats: [
            {
                status: "Launched",
                minimumBuy: "1",
                maxiumumBuy: "50",
                presaleRate: "2,500,000 $SCOT",
                listingRate: "2,500,000 $SCOT",
                totalContributors: 94,
                avgContribution: 10.33111,
                myContribution: 0,
                myReservedTokens: 0,
                tokenAddress: "0x64F7e4B5B48654c45476ADbc7800a78D3f577C8d",
            },
        ],
        launched: {
            tokenAddress: "EoJEyppNNpycP1ZoPnWq6cxwA7mSYpr9T1WXPFyjEzEy",
            listingDex: "Orca",
            listingDexImage: "scottish-cat/Orca.png",
            chart: "Dextools",
            chartImage: "scottish-cat/Dextools.png",
            mintable: false,
            freezable: false,
        },
        updates: [
            {
                id: 1,
                dateFrom: "3 months ago",
                content:
                    "If you need assets on Abey - 1. Bridge USDT on XPlus (https://x.plus) 2. Or purchase ABEY on LBank (https://lbank.com/trade/abey_usdt) then sell on XSwap (https://xswap.com)",
            },
        ],
    },
    {
        id: 5,
        banner: "strike-protocol/strike-protocol-banner.webp",
        logo: "strike-protocol/strike-protocol-logo.png",
        networkLogo: "strike-protocol/eth.webp",
        typeImage: "/strike-protocol/3.svg",
        title: "Strike Protocol",
        type: "Bonus Presale",
        maxBuy: 50000,
        status: "launched",
        progress: 74,
        tags: ["KYC+", "AUDIT", "VETTED"],
        target: 100,
        raised: 100,
        softcap: 300000,
        currency: "ETH",
        hardcap: "1M",
        rate: "2ITW",
        lock: "Manual",
        address: "0x3D9029C5D43e178688A40a582223c96B5e391C97",
        network: "ethscan",
        tabs: [
            {
                id: 1,
                name: "About",
                content:
                    "Get ready to explore the fascinating world of Strike Protocol. This groundbreaking multiplayer adventure seamlessly blends managing your base in an open sandbox environment with the thrill of raiding champion bases. In this gripping experience, players go beyond just playing – they conquer, taking on the roles of skilled Infiltrators or strategic Commanders. Whether you are building challenging bases or embarking on daring missions to dominate the creations of other players, get ready for an epic gaming journey.",
                ytVideo: "https://youtu.be/KM1ESh1zqo0",
            },
            {
                id: 2,
                name: "Sale",
                network: "ethscan",
                presaleAddress: "0x3D9029C5D43e178688A40a582223c96B5e391C97",
                tokenName: "StrikeProtocol",
                tokenSymbol: "STPR",
                totalSupply: 1000000000,
                tokensForPresale: 318000000,
                tokensForLiquidity: 95999700,

                softcap: 30,
                hardcap: 100,
                unusedTokens: "Burn",
                presaleStartTime: "2024-03-19 19:00",
                presaleEndTime: "2024-03-21 18:00",
                liquidityPercent: "33.33322916666667%",
                liquidityUnlockTime: "2024-09-17 20:00",

            },
            {
                id: 3,
                name: "Tokenomics",
                presale: 33.4849,
                unlocked: 26.7047,
                liquidity: 9.6,
                locked: 30,
                burnt: 0.2105,
                initialMarketCap: 0,
                circulatingMarketCap: 0,
                fdvMarketCap: 0,
            },
            {
                id: 4,
                name: "Locks",
                tokenLocks: 0,
                liquidityLocks: 0,
                tokenSymbol: "STPR",
            },
            {
                id: 5,
                name: "Team",
                members: [
                    {
                        name: "Interworld",
                        title: "Owner",
                        twitter: "https://twitter.com/interworld_io",
                        avatar: "strike-protocol/strike-protocol-logo.png",
                    },
                ],
            },
        ],
        stats: [
            {
                status: "finalized",
                minimumBuy: "50",
                maxiumumBuy: "50",
                presaleRate: "2ITW",
                listingRate: "2ITW",
                totalContributors: 1272,
                avgContribution: 78616352,
                myContribution: 0,
                myReservedTokens: 0,
                tokenAddress: "0x64F7e4B5B48654c45476ADbc7800a78D3f577C8d",
            },
        ],
        updates: [
            {
                id: 1,
                dateFrom: "3 months ago",
                content:
                    "If you need assets on Abey - 1. Bridge USDT on XPlus (https://x.plus) 2. Or purchase ABEY on LBank (https://lbank.com/trade/abey_usdt) then sell on XSwap (https://xswap.com)",
            },
        ],
    }
];